markdown: redcarpet
permalink: /:categories/:title.html
url: 
lsi: false
pygments: true
safe: true
auto: false 

paginate: 8
paginate_path: "page:num"

# presonal config
domain: sheshiji.github.io
title: 佑顺屋
description: C/C++, Qt, Java, Linux, Reading...
author: sheshiji
email: sheshiji#gmail.com
github: sheshiji

config:
  js_dir:
  img_dir:
  css_dir:
